name: 'ovara'
version: '1.0.0'
config-version: 2

profile: 'ovara'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ovara:
    stg:
      +schema: stg
      +materialized: incremental
    dw:
      +schema: dw
    int:
      +schema: int
    pub:
      +schema: pub
      +materialized: table
