name: Run current installed DBT Runner task

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: 'Environment which to deploy to (testi/tuotanto)'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment which to deploy to'
        options:
          - testi
          - tuotanto

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Run current installed DBT Runner task
    runs-on: ubuntu-latest  
